name: Build and Push Images + Update K8s Manifests

on:
  push:
    branches: [ master ]

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/mern-backend
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/mern-nginx

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        run: echo "TAG=release-$(date +%s)" >> $GITHUB_ENV

      - name: Build & Push Backend Image
        run: |
          docker build -t $IMAGE_BACKEND:$TAG ./server
          docker push $IMAGE_BACKEND:$TAG

      - name: Build & Push Frontend (Nginx) Image
        run: |
          docker build -t $IMAGE_FRONTEND:$TAG -f nginx/Dockerfile .
          docker push $IMAGE_FRONTEND:$TAG

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: .*mern-backend:.*|image: $IMAGE_BACKEND:$TAG|" K8s/backend-deployment.yml
          sed -i "s|image: .*mern-nginx:.*|image: $IMAGE_FRONTEND:$TAG|" K8s/frontend-deployment.yml

      - name: Commit and Push Updated Manifests
        run: |
          git config user.name "mas00m007"
          git config user.email "masoom.kcis@gmail.com"
          git commit -am "ci: update images to $TAG"
          git push
